Description: Create an EC2 instance by AWS CloudFormation
Resources:
  SecurityGroupDemoSvrTraffic:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: Jenkins-SG1
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
          Description: For traffic from Internet
      GroupDescription: Security Group for demo server
      VpcId: vpc-afb094d7
  EC2InstanceDemoSvr:
    Type: 'AWS::EC2::Instance'
    Properties:
      AvailabilityZone: us-west-2a
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            DeleteOnTermination: 'true'
            VolumeSize: '8'
            VolumeType: gp2
      ImageId: ami-089618304e65b26ac
      InstanceType: t2.micro
      KeyName: OpenVPN-Demo
      UserData: 
       Fn::Base64: |
        #!/bin/sh
        cat <<'EOF' > /etc/apache2/sites-available/planhub-frontend-waf.conf
        <VirtualHost *:80>
	ServerName qa1.planhub.com
	ServerAlias qa1.planhub.com
	DocumentRoot /var/www/html/frontend-planhub-new/dist
	ErrorLog ${APACHE_LOG_DIR}/error.log
      	CustomLog ${APACHE_LOG_DIR}/access.log cloudwatch
        RewriteEngine On
        RewriteCond %{HTTP:X-Forwarded-Proto} =http
        RewriteRule .* https://%{HTTP:Host}%{REQUEST_URI} [L,R=permanent]
        </VirtualHost>
        <VirtualHost *:443>
        DocumentRoot /var/www/html/frontend-planhub-new/dist
        ServerName app.planhub.com
        ServerAlias app.planhub.com
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log cloudwatch
        RewriteEngine On
        RewriteRule ^#/(.*)$ $1
        SSLEngine on
        SSLCertificateFile /etc/apache2/ssl/NEW_STAR_planhub_com.crt
        SSLCertificateKeyFile /etc/apache2/ssl/new_star.planhub.com.key
        SSLCertificateChainFile  /etc/apache2/ssl/planhub_intermediate.crt
        SSLCipherSuite HIGH:+MEDIUM:!SSLv2:!EXP:!ADH:!aNULL:!eNULL:!NULL
        Header always set Strict-Transport-Security "max-age=63072000;"
        SSLProtocol all -SSLv2 -SSLv3
        SSLHonorCipherOrder on
        SSLCipherSuite "EECDH+ECDSA+AESGCM EECDH+aRSA+AESGCM EECDH+ECDSA+SHA384 EECDH+ECDSA+SHA256 EECDH+aRSA+S$
        <Directory  /var/www/html/frontend-planhub-new>
        AllowOverride All
        Require all granted
        RewriteEngine On
        RewriteRule ^(.*)$ $1
        </Directory>
        <IfModule mod_deflate.c>
        SetOutputFilter DEFLATE
        AddOutputFilterByType DEFLATE text/plain
        AddOutputFilterByType DEFLATE text/html
        AddOutputFilterByType DEFLATE text/xml
        AddOutputFilterByType DEFLATE text/css
        AddOutputFilterByType DEFLATE application/xml
        AddOutputFilterByType DEFLATE application/xhtml+xml
        AddOutputFilterByType DEFLATE application/rss+xml
        AddOutputFilterByType DEFLATE application/javascript
        AddOutputFilterByType DEFLATE application/x-javascript
        SetEnvIfNoCase Request_URI .(?:exe|t?gz|zip|iso|tar|bz2|sit|rar) no-gzip dont-vary
        SetEnvIfNoCase Request_URI .(?:gif|jpe?g|jpg|ico|png)  no-gzip dont-vary
        SetEnvIfNoCase Request_URI .pdf no-gzip dont-vary
        BrowserMatch ^Mozilla/4 gzip-only-text/html
        BrowserMatch ^Mozilla/4.0[678] no-gzip
        BrowserMatch \bMSIE !no-gzip !gzip-only-text/html
        Header append Vary User-Agent env=!dont-vary
        DeflateFilterNote Input instr
        DeflateFilterNote Output outstr
        DeflateFilterNote Ratio ratio
        LogFormat '"%r" %{outstr}n/%{instr}n %{ratio}n%%' DEFLATE
        CustomLog logs/deflate_log DEFLATE
        </IfModule>
        </VirtualHost>
        EOF
        cat <<'EOF' > /etc/apache2/sites-available/planhub-frontend-waf.conf
        <VirtualHost *:80>
        ServerName qa1.api.planhub.com
        ServerAlias qa1.api.planhub.com 
        DocumentRoot /var/www/html/api-planhub/public   
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log cloudwatch
        RewriteEngine On
        RewriteCond %{HTTP:X-Forwarded-Proto} =http
        RewriteRule .* https://%{HTTP:Host}%{REQUEST_URI} [L,R=permanent]
        </VirtualHost>
        <VirtualHost *:443>
        DocumentRoot /var/www/html/api-planhub/public
        ServerName api.planhub.com
        ServerAlias api.planhub.com
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log cloudwatch
        SSLEngine on
        SSLCertificateFile /etc/apache2/ssl/NEW_STAR_planhub_com.crt
        SSLCertificateKeyFile /etc/apache2/ssl/new_star.planhub.com.key
        SSLCertificateChainFile  /etc/apache2/ssl/planhub_intermediate.crt
        SSLCipherSuite HIGH:+MEDIUM:!SSLv2:!EXP:!ADH:!aNULL:!eNULL:!NULL
        Header always set Strict-Transport-Security "max-age=63072000;"
        SSLProtocol all -SSLv2 -SSLv3
        SSLHonorCipherOrder on
        SSLCipherSuite "EECDH+ECDSA+AESGCM EECDH+aRSA+AESGCM EECDH+ECDSA+SHA384 EECDH+ECDSA+SHA256 EECDH+aRSA+S$
        <Directory /var/www/html/api-planhub/public>
        AllowOverride All
        Options Indexes FollowSymLinks
        Require all granted
        RewriteEngine On
        RewriteBase /
        RewriteCond %{RREQUEST_FILENAME} !-d
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteRule ^ index.php [QSA,L]
        RewriteRule .*\.(pdf|css|gif|png|bmp)$ - [F,NC]
        RewriteCond %{REQUEST_METHOD} OPTIONS
        RewriteRule ^(.*)$ $1 [R=200,L]
        </Directory>
        <IfModule mod_deflate.c>
        SetOutputFilter DEFLATE
        AddOutputFilterByType DEFLATE text/plain
        AddOutputFilterByType DEFLATE text/html
        AddOutputFilterByType DEFLATE text/xml
        AddOutputFilterByType DEFLATE text/css
        AddOutputFilterByType DEFLATE text/xml
        AddOutputFilterByType DEFLATE text/css
        AddOutputFilterByType DEFLATE application/xml
        AddOutputFilterByType DEFLATE application/xhtml+xml
        AddOutputFilterByType DEFLATE application/rss+xml
        AddOutputFilterByType DEFLATE application/javascript
        AddOutputFilterByType DEFLATE application/x-javascript
        SetEnvIfNoCase Request_URI .(?:exe|t?gz|zip|iso|tar|bz2|sit|rar) no-gzip dont-vary
        SetEnvIfNoCase Request_URI .(?:gif|jpe?g|jpg|ico|png)  no-gzip dont-vary
        SetEnvIfNoCase Request_URI .pdf no-gzip dont-vary
        BrowserMatch ^Mozilla/4 gzip-only-text/html
        BrowserMatch ^Mozilla/4.0[678] no-gzip
        BrowserMatch \bMSIE !no-gzip !gzip-only-text/html
        Header append Vary User-Agent env=!dont-vary
        DeflateFilterNote Input instr
        DeflateFilterNote Output outstr
        DeflateFilterNote Ratio ratio
        LogFormat '"%r" %{outstr}n/%{instr}n %{ratio}n%%' DEFLATE
        CustomLog logs/deflate_log DEFLATE
        Header set Access-Control-Allow-Origin "*"
        </IfModule> 
        </VirtualHost>
        systemctl restart apache2
      NetworkInterfaces:
        - Description: Primary network interface
          DeviceIndex: '0'
          SubnetId: subnet-13ad7f59
          PrivateIpAddress: 172.31.46.64
          GroupSet:
            - !Ref SecurityGroupDemoSvrTraffic
